// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB02XCSzjp9aYQgUvteh10krzOCTs74mA',
    appId: '1:948011349278:web:081934d95fbabc6d52850f',
    messagingSenderId: '948011349278',
    projectId: 'dashboardflutter-78999',
    authDomain: 'dashboardflutter-78999.firebaseapp.com',
    storageBucket: 'dashboardflutter-78999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB02XCSzjp9aYQgUvteh10krzOCTs74mA', // Usar la misma API key
    appId:
        '1:948011349278:android:ANDROID_APP_ID', // Necesitarás crear app Android en Firebase
    messagingSenderId: '948011349278',
    projectId: 'dashboardflutter-78999',
    storageBucket: 'dashboardflutter-78999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB02XCSzjp9aYQgUvteh10krzOCTs74mA',
    appId:
        '1:948011349278:ios:IOS_APP_ID', // Necesitarás crear app iOS en Firebase
    messagingSenderId: '948011349278',
    projectId: 'dashboardflutter-78999',
    storageBucket: 'dashboardflutter-78999.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB02XCSzjp9aYQgUvteh10krzOCTs74mA',
    appId:
        '1:948011349278:macos:MACOS_APP_ID', // Necesitarás crear app macOS en Firebase
    messagingSenderId: '948011349278',
    projectId: 'dashboardflutter-78999',
    storageBucket: 'dashboardflutter-78999.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB02XCSzjp9aYQgUvteh10krzOCTs74mA',
    appId: '1:948011349278:web:081934d95fbabc6d52850f',
    messagingSenderId: '948011349278',
    projectId: 'dashboardflutter-78999',
    authDomain: 'dashboardflutter-78999.firebaseapp.com',
    storageBucket: 'dashboardflutter-78999.firebasestorage.app',
  );
}
